window.SAOD_LOCAL_DATABASE = {
  "users": [
    {
      "id": "USR-000",
      "name": "Admin",
      "email": "admin@saod.com",
      "password": "admin123",
      "role": "admin",
      "joined": ""
    },
    {
      "id": "USR-001",
      "name": "Lorenz Saguindel",
      "email": "lorenz@saod.com",
      "password": "lorenz123",
      "role": "vendor",
      "joined": "",
      "company": "SAOD Market"
    }
  ],
  "products": [
    {
      "id": "PRD-001",
      "name": "Fresh Tomatoes",
      "category": "Vegetables",
      "price": 95,
      "stock": 40,
      "desc": "Ripe local tomatoes for cooking and salads.",
      "stockUnit": "kg",
      "priceUnit": "per kg",
      "vendorId": "USR-001",
      "vendorName": "Lorenz Saguindel",
      "date": ""
    },
    {
      "id": "PRD-002",
      "name": "Baguio Pechay",
      "category": "Vegetables",
      "price": 80,
      "stock": 35,
      "desc": "Crisp leafy pechay packed fresh.",
      "stockUnit": "kg",
      "priceUnit": "per kg",
      "vendorId": "USR-001",
      "vendorName": "Lorenz Saguindel",
      "date": ""
    },
    {
      "id": "PRD-003",
      "name": "Carrots",
      "category": "Vegetables",
      "price": 110,
      "stock": 30,
      "desc": "Sweet orange carrots for soups and stir fry.",
      "stockUnit": "kg",
      "priceUnit": "per kg",
      "vendorId": "USR-001",
      "vendorName": "Lorenz Saguindel",
      "date": ""
    },
    {
      "id": "PRD-004",
      "name": "Lakatan Bananas",
      "category": "Fruits",
      "price": 120,
      "stock": 45,
      "desc": "Sweet ripe bananas sold by kilogram.",
      "stockUnit": "kg",
      "priceUnit": "per kg",
      "vendorId": "USR-001",
      "vendorName": "Lorenz Saguindel",
      "date": ""
    },
    {
      "id": "PRD-005",
      "name": "Mangoes",
      "category": "Fruits",
      "price": 180,
      "stock": 28,
      "desc": "Golden mangoes with fragrant sweet flesh.",
      "stockUnit": "kg",
      "priceUnit": "per kg",
      "vendorId": "USR-001",
      "vendorName": "Lorenz Saguindel",
      "date": ""
    },
    {
      "id": "PRD-006",
      "name": "Pineapple",
      "category": "Fruits",
      "price": 85,
      "stock": 22,
      "desc": "Whole pineapple, juicy and ready to slice.",
      "stockUnit": "unit",
      "priceUnit": "per unit",
      "vendorId": "USR-001",
      "vendorName": "Lorenz Saguindel",
      "date": ""
    },
    {
      "id": "PRD-007",
      "name": "Chicken Breast",
      "category": "Meat & Poultry",
      "price": 240,
      "stock": 25,
      "desc": "Boneless chicken breast, chilled and packed.",
      "stockUnit": "kg",
      "priceUnit": "per kg",
      "vendorId": "USR-001",
      "vendorName": "Lorenz Saguindel",
      "date": ""
    },
    {
      "id": "PRD-008",
      "name": "Pork Belly",
      "category": "Meat & Poultry",
      "price": 360,
      "stock": 20,
      "desc": "Fresh pork belly cuts for grilling or adobo.",
      "stockUnit": "kg",
      "priceUnit": "per kg",
      "vendorId": "USR-001",
      "vendorName": "Lorenz Saguindel",
      "date": ""
    },
    {
      "id": "PRD-009",
      "name": "Beef Sirloin",
      "category": "Meat & Poultry",
      "price": 520,
      "stock": 15,
      "desc": "Tender beef sirloin slices for quick meals.",
      "stockUnit": "kg",
      "priceUnit": "per kg",
      "vendorId": "USR-001",
      "vendorName": "Lorenz Saguindel",
      "date": ""
    },
    {
      "id": "PRD-010",
      "name": "Tilapia",
      "category": "Seafood",
      "price": 150,
      "stock": 30,
      "desc": "Fresh whole tilapia cleaned on request.",
      "stockUnit": "kg",
      "priceUnit": "per kg",
      "vendorId": "USR-001",
      "vendorName": "Lorenz Saguindel",
      "date": ""
    },
    {
      "id": "PRD-011",
      "name": "Shrimp",
      "category": "Seafood",
      "price": 420,
      "stock": 18,
      "desc": "Medium shrimp for saute, soup, or grilling.",
      "stockUnit": "kg",
      "priceUnit": "per kg",
      "vendorId": "USR-001",
      "vendorName": "Lorenz Saguindel",
      "date": ""
    },
    {
      "id": "PRD-012",
      "name": "Squid",
      "category": "Seafood",
      "price": 310,
      "stock": 16,
      "desc": "Fresh squid, cleaned and chilled.",
      "stockUnit": "kg",
      "priceUnit": "per kg",
      "vendorId": "USR-001",
      "vendorName": "Lorenz Saguindel",
      "date": ""
    },
    {
      "id": "PRD-013",
      "name": "Fresh Milk",
      "category": "Dairy",
      "price": 95,
      "stock": 32,
      "desc": "One liter chilled fresh milk.",
      "stockUnit": "L",
      "priceUnit": "per L",
      "vendorId": "USR-001",
      "vendorName": "Lorenz Saguindel",
      "date": ""
    },
    {
      "id": "PRD-014",
      "name": "Cheddar Cheese",
      "category": "Dairy",
      "price": 140,
      "stock": 24,
      "desc": "Creamy cheddar block for sandwiches and cooking.",
      "stockUnit": "unit",
      "priceUnit": "per unit",
      "vendorId": "USR-001",
      "vendorName": "Lorenz Saguindel",
      "date": ""
    },
    {
      "id": "PRD-015",
      "name": "Plain Yogurt",
      "category": "Dairy",
      "price": 75,
      "stock": 30,
      "desc": "Unsweetened yogurt cup for snacks or breakfast.",
      "stockUnit": "unit",
      "priceUnit": "per unit",
      "vendorId": "USR-001",
      "vendorName": "Lorenz Saguindel",
      "date": ""
    },
    {
      "id": "PRD-016",
      "name": "Jasmine Rice",
      "category": "Grains & Rice",
      "price": 68,
      "stock": 100,
      "desc": "Fragrant jasmine rice sold per kilogram.",
      "stockUnit": "kg",
      "priceUnit": "per kg",
      "vendorId": "USR-001",
      "vendorName": "Lorenz Saguindel",
      "date": ""
    },
    {
      "id": "PRD-017",
      "name": "Brown Rice",
      "category": "Grains & Rice",
      "price": 82,
      "stock": 75,
      "desc": "Whole grain brown rice for healthier meals.",
      "stockUnit": "kg",
      "priceUnit": "per kg",
      "vendorId": "USR-001",
      "vendorName": "Lorenz Saguindel",
      "date": ""
    },
    {
      "id": "PRD-018",
      "name": "Rolled Oats",
      "category": "Grains & Rice",
      "price": 130,
      "stock": 40,
      "desc": "Rolled oats for breakfast bowls and baking.",
      "stockUnit": "unit",
      "priceUnit": "per unit",
      "vendorId": "USR-001",
      "vendorName": "Lorenz Saguindel",
      "date": ""
    },
    {
      "id": "PRD-019",
      "name": "Bottled Water",
      "category": "Beverages",
      "price": 25,
      "stock": 120,
      "desc": "One liter purified drinking water.",
      "stockUnit": "unit",
      "priceUnit": "per unit",
      "vendorId": "USR-001",
      "vendorName": "Lorenz Saguindel",
      "date": ""
    },
    {
      "id": "PRD-020",
      "name": "Calamansi Juice",
      "category": "Beverages",
      "price": 60,
      "stock": 50,
      "desc": "Refreshing calamansi drink in a bottle.",
      "stockUnit": "unit",
      "priceUnit": "per unit",
      "vendorId": "USR-001",
      "vendorName": "Lorenz Saguindel",
      "date": ""
    },
    {
      "id": "PRD-021",
      "name": "Iced Tea",
      "category": "Beverages",
      "price": 55,
      "stock": 55,
      "desc": "Ready-to-drink iced tea bottle.",
      "stockUnit": "unit",
      "priceUnit": "per unit",
      "vendorId": "USR-001",
      "vendorName": "Lorenz Saguindel",
      "date": ""
    },
    {
      "id": "PRD-022",
      "name": "Banana Chips",
      "category": "Snacks",
      "price": 70,
      "stock": 45,
      "desc": "Crispy sweet banana chips pack.",
      "stockUnit": "unit",
      "priceUnit": "per unit",
      "vendorId": "USR-001",
      "vendorName": "Lorenz Saguindel",
      "date": ""
    },
    {
      "id": "PRD-023",
      "name": "Peanut Brittle",
      "category": "Snacks",
      "price": 85,
      "stock": 36,
      "desc": "Crunchy peanut brittle pack.",
      "stockUnit": "unit",
      "priceUnit": "per unit",
      "vendorId": "USR-001",
      "vendorName": "Lorenz Saguindel",
      "date": ""
    },
    {
      "id": "PRD-024",
      "name": "Cassava Chips",
      "category": "Snacks",
      "price": 65,
      "stock": 42,
      "desc": "Lightly salted cassava chips.",
      "stockUnit": "unit",
      "priceUnit": "per unit",
      "vendorId": "USR-001",
      "vendorName": "Lorenz Saguindel",
      "date": ""
    },
    {
      "id": "PRD-025",
      "name": "Cooking Oil",
      "category": "Other",
      "price": 180,
      "stock": 35,
      "desc": "One liter bottle of cooking oil.",
      "stockUnit": "L",
      "priceUnit": "per L",
      "vendorId": "USR-001",
      "vendorName": "Lorenz Saguindel",
      "date": ""
    },
    {
      "id": "PRD-026",
      "name": "Brown Sugar",
      "category": "Other",
      "price": 78,
      "stock": 60,
      "desc": "Brown sugar for cooking, baking, and drinks.",
      "stockUnit": "kg",
      "priceUnit": "per kg",
      "vendorId": "USR-001",
      "vendorName": "Lorenz Saguindel",
      "date": ""
    },
    {
      "id": "PRD-027",
      "name": "Soy Sauce",
      "category": "Other",
      "price": 45,
      "stock": 50,
      "desc": "All-purpose soy sauce bottle.",
      "stockUnit": "unit",
      "priceUnit": "per unit",
      "vendorId": "USR-001",
      "vendorName": "Lorenz Saguindel",
      "date": ""
    }
  ],
  "orders": [],
  "payments": [],
  "deliveries": [],
  "id_seq": {
    "users": 1,
    "products": 27,
    "orders": 0,
    "payments": 0,
    "deliveries": 0
  }
};

